changelog:
  exclude:
    authors:
      - dependabot[bot]
      - pre-commit-ci[bot]
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Documentation
      labels:
        - Documentation
    - title: Other Changes
      labels:
        - "*"
